# Generated by Django 5.2.17 on 2026-09-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='running', max_length=16)),
                ('categories', models.JSONField(default=list, help_text='arXiv categories requested for this run')),
                ('papers_seen', models.PositiveIntegerField(default=0)),
                ('papers_created', models.PositiveIntegerField(default=0)),
                ('papers_updated', models.PositiveIntegerField(default=0)),
                ('papers_skipped', models.PositiveIntegerField(default=0, help_text='Content hash unchanged, so no work was needed')),
                ('chunks_indexed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='manual', help_text='scheduler, manual, backfill, test', max_length=64)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('git_sha', models.CharField(db_index=True, help_text='The commit these numbers came from. A metric that cannot be traced to a specific revision cannot be reproduced, and a number that cannot be reproduced should not be quoted.', max_length=40)),
                ('golden_set_version', models.CharField(help_text='Golden set file version. Comparing runs across different versions is invalid.', max_length=32)),
                ('mode', models.CharField(choices=[('bm25', 'BM25 keyword'), ('dense', 'Dense vector'), ('hybrid', 'Hybrid (RRF)')], db_index=True, max_length=16)),
                ('num_queries', models.PositiveIntegerField()),
                ('metrics', models.JSONField(default=dict, help_text='Aggregate and per-class metrics: recall@k, MRR, nDCG@10. JSON rather than columns because the metric set is still changing, and a migration per new metric would discourage adding them.')),
                ('is_baseline', models.BooleanField(default=False, help_text='Marks the run the CI regression gate compares against')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['mode', '-started_at'], name='papers_eval_mode_d47b6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(db_index=True, help_text='arXiv identifier including version, e.g. 2401.12345v2', max_length=32, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('primary_category', models.CharField(db_index=True, max_length=32)),
                ('published_at', models.DateTimeField(help_text='When the first version was submitted to arXiv')),
                ('arxiv_updated_at', models.DateTimeField(help_text='When the most recent version was submitted')),
                ('abs_url', models.URLField(max_length=500)),
                ('pdf_url', models.URLField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 of title + abstract. Ingestion compares this before doing any work: an unchanged hash means the paper can be skipped without re-embedding it. This is what makes the pipeline safe to re-run.', max_length=64)),
                ('indexed_at', models.DateTimeField(blank=True, help_text='When this paper was last written to the search index. NULL means it exists in Postgres but is not yet searchable - the two stores can legitimately disagree mid-run, and this field records that.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['primary_category', '-published_at'], name='papers_pape_primary_d2f7e3_idx'), models.Index(fields=['indexed_at'], name='papers_pape_indexed_d59a5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='Position within the paper. Always 0 while one chunk per paper.')),
                ('text', models.TextField(help_text='Exactly the text that was embedded')),
                ('token_count', models.PositiveIntegerField(blank=True, help_text='Recorded to detect silent truncation by the embedding model', null=True)),
                ('embedding_model', models.CharField(help_text='Which model produced the vector. Stored per chunk because a model change invalidates every vector produced by the previous one, and mixing them in a single index produces meaningless neighbours.', max_length=128)),
                ('embedding_dim', models.PositiveIntegerField()),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper')),
            ],
            options={
                'ordering': ['paper', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'chunk_index'), name='unique_chunk_per_paper_position')],
            },
        ),
    ]
