# Generated by Django 5.2.17 on 2026-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='papers_split',
            field=models.PositiveIntegerField(default=0, help_text="Papers whose text exceeded the embedding model's context window and had to be sentence-split. Counted because the alternative is the model silently truncating them, which degrades retrieval for a subset of documents with nothing in any log to explain it."),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='watermark',
            field=models.DateTimeField(blank=True, help_text='Newest publication date this run saw. The next run queries arXiv forward from here instead of re-scanning the whole category. Set only on a successful run - advancing it after a failure would skip everything the failed run never reached.', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, help_text='arXiv version number. 2401.12345v3 is stored as arxiv_id + version 3.'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(db_index=True, help_text="Canonical arXiv identifier with the version suffix stripped, e.g. 2401.12345. This is the paper's stable identity and what ingestion upserts on. Keying on the versioned form instead would make every revision look like a new paper and fill the corpus with duplicates.", max_length=32, unique=True),
        ),
    ]
