/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evaluation-runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List evaluation runs
         * @description Retrieval quality over time, per retriever mode.
         */
        get: operations["evaluation_runs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation-runs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve one evaluation run
         * @description Retrieval quality over time, per retriever mode.
         */
        get: operations["evaluation_runs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and readiness probe
         * @description Returns 200 when the service can reach its database, 503 otherwise. Used by the container health check and by uptime monitoring.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion-runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ingestion runs
         * @description Harvest history.
         *
         *     Exposed over HTTP so that pipeline health is observable without database
         *     access, which matters once this is running somewhere other than a laptop.
         */
        get: operations["ingestion_runs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion-runs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve one ingestion run
         * @description Harvest history.
         *
         *     Exposed over HTTP so that pipeline health is observable without database
         *     access, which matters once this is running somewhere other than a laptop.
         */
        get: operations["ingestion_runs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List papers
         * @description Browse the indexed corpus.
         */
        get: operations["papers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{arxiv_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve one paper by arXiv ID
         * @description Browse the indexed corpus.
         */
        get: operations["papers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search the corpus
         * @description Retrieve papers by keyword (bm25), meaning (dense), or both fused with Reciprocal Rank Fusion (hybrid). The mode parameter is what makes the published ablation a measurement of this endpoint rather than of a parallel implementation.
         */
        post: operations["search_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One measured sweep, with the provenance needed to reproduce it. */
        EvaluationRun: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string;
            mode: components["schemas"]["EvaluationRunModeEnum"];
            top_k: number;
            golden_set_version: number;
            corpus_papers: number;
            corpus_chunks: number;
            git_sha?: string;
            metrics?: unknown;
            notes?: string;
        };
        /**
         * @description * `bm25` - Lexical (BM25)
         *     * `dense` - Dense (pgvector)
         *     * `hybrid` - Hybrid (RRF)
         * @enum {string}
         */
        EvaluationRunModeEnum: "bm25" | "dense" | "hybrid";
        IngestionRun: {
            readonly id: number;
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: double */
            readonly duration_seconds: number;
            status?: components["schemas"]["StatusEnum"];
            /** @description arXiv categories requested for this run */
            categories?: unknown;
            papers_seen?: number;
            papers_created?: number;
            papers_updated?: number;
            /** @description Content hash unchanged, so no work was needed */
            papers_skipped?: number;
            /** @description Papers whose text exceeded the embedding model's context window and had to be sentence-split. Counted because the alternative is the model silently truncating them, which degrades retrieval for a subset of documents with nothing in any log to explain it. */
            papers_split?: number;
            chunks_indexed?: number;
            /**
             * Format: date-time
             * @description Newest publication date this run saw. The next run queries arXiv forward from here instead of re-scanning the whole category. Set only on a successful run - advancing it after a failure would skip everything the failed run never reached.
             */
            watermark?: string | null;
            /** @description scheduler, manual, backfill, test */
            triggered_by?: string;
            error_message?: string;
        };
        PaginatedEvaluationRunList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["EvaluationRun"][];
        };
        PaginatedIngestionRunList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IngestionRun"][];
        };
        PaginatedPaperListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PaperList"][];
        };
        /** @description Full representation, including indexing state. */
        PaperDetail: {
            /** @description Canonical arXiv identifier with the version suffix stripped, e.g. 2401.12345. This is the paper's stable identity and what ingestion upserts on. Keying on the versioned form instead would make every revision look like a new paper and fill the corpus with duplicates. */
            arxiv_id: string;
            /** @description arXiv version number. 2401.12345v3 is stored as arxiv_id + version 3. */
            version?: number;
            title: string;
            abstract: string;
            authors?: unknown;
            categories?: unknown;
            primary_category: string;
            /**
             * Format: date-time
             * @description When the first version was submitted to arXiv
             */
            published_at: string;
            /**
             * Format: date-time
             * @description When the most recent version was submitted
             */
            arxiv_updated_at: string;
            /** Format: uri */
            abs_url: string;
            /** Format: uri */
            pdf_url: string;
            /** @description SHA-256 of title + abstract. Ingestion compares this before doing any work: an unchanged hash means the paper can be skipped without re-embedding it. This is what makes the pipeline safe to re-run. */
            readonly content_hash: string;
            /**
             * Format: date-time
             * @description When this paper was last written to the search index. NULL means it exists in Postgres but is not yet searchable - the two stores can legitimately disagree mid-run, and this field records that.
             */
            indexed_at?: string | null;
            readonly needs_indexing: boolean;
            readonly chunk_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Light representation for result lists. */
        PaperList: {
            /** @description Canonical arXiv identifier with the version suffix stripped, e.g. 2401.12345. This is the paper's stable identity and what ingestion upserts on. Keying on the versioned form instead would make every revision look like a new paper and fill the corpus with duplicates. */
            arxiv_id: string;
            title: string;
            authors?: unknown;
            primary_category: string;
            categories?: unknown;
            /**
             * Format: date-time
             * @description When the first version was submitted to arXiv
             */
            published_at: string;
            /** Format: uri */
            abs_url: string;
            /** @description First 300 characters, cut on a word boundary. */
            readonly abstract_snippet: string;
        };
        /**
         * @description * `bm25` - bm25
         *     * `dense` - dense
         *     * `hybrid` - hybrid
         * @enum {string}
         */
        SearchRequestModeEnum: "bm25" | "dense" | "hybrid";
        /** @description What a client may ask for. */
        SearchRequestRequest: {
            /** @description Natural-language query. */
            query: string;
            /**
             * @description Retrieval strategy. Exposed because it is the ablation mechanism: the evaluation harness calls this endpoint once per mode, so the measured system is the served system.
             *
             *     * `bm25` - bm25
             *     * `dense` - dense
             *     * `hybrid` - hybrid
             * @default hybrid
             */
            mode: components["schemas"]["SearchRequestModeEnum"];
            /**
             * @description How many results to return.
             * @default 10
             */
            top_k: number;
        };
        /** @description The envelope. */
        SearchResponse: {
            query: string;
            mode: string;
            top_k: number;
            count: number;
            /** Format: double */
            took_ms: number;
            diagnostics: {
                [key: string]: unknown;
            };
            results: components["schemas"]["SearchResult"][];
        };
        /** @description One result, with the paper metadata needed to render it. */
        SearchResult: {
            arxiv_id: string;
            rank: number;
            /** Format: double */
            score: number;
            title: string;
            abstract: string;
            authors: string[];
            primary_category: string;
            /** Format: date-time */
            published_at: string;
            /** Format: uri */
            abs_url: string;
            /** @description Per-retriever rank and score detail. For hybrid, this shows which retrievers found the paper and what each contributed to its fused score - the data behind the 'why this result' panel, and the first thing to read when a ranking looks wrong. */
            debug: {
                [key: string]: unknown;
            };
        };
        /**
         * @description * `running` - Running
         *     * `success` - Success
         *     * `failed` - Failed
         *     * `partial` - Partial
         * @enum {string}
         */
        StatusEnum: "running" | "success" | "failed" | "partial";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evaluation_runs_list: {
        parameters: {
            query?: {
                /** @description Filter to one retriever mode: bm25, dense or hybrid. */
                mode?: "bm25" | "dense" | "hybrid";
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEvaluationRunList"];
                };
            };
        };
    };
    evaluation_runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this evaluation run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingestion_runs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngestionRunList"];
                };
            };
        };
    };
    ingestion_runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    papers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaperListList"];
                };
            };
        };
    };
    papers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
        };
    };
    search_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SearchRequestRequest"];
                "multipart/form-data": components["schemas"]["SearchRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
